### ISSUE TITLE
[BUG] Creation of SDK for SAP S/4HANA Cloud - Customer Material (A2X) API fails

### ISSUE THREAD

**Issue by gregorwolf** [WillEastbury/odata-openapi#4]
**Describe the bug**

I've tried to create the TypeScript SDK for the SAP S/4HANA Cloud - Customer Material (A2X) API. But it fails with this error in the POST request to https://convert.odata-openapi.net/api/CodeGen:

```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\home\c:\site\wwwroot\node_modules\autorest\entrypoints\app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**To Reproduce**

1. Go to [SAP S/4HANA Cloud - Customer Material (A2X)](https://api.sap.com/api/API_CUSTOMER_MATERIAL_SRV/overview) and download the EDMX from the API specification
2. Open https://convert.odata-openapi.net/# and switch to SDK Generator
3. Paste the EDMX content into 'Manual Input of OData Definition'
4. Click Generate SDK and choose Typescript
5. See error

**Expected behavior**

No error should occur.

**Desktop (please complete the following information):**

 - OS: MacOS 13.4.1
 - Browser Chrome
 - Version Version 116.0.5845.96 (Official Build) (arm64)

**OData Payload for diagnosis**

As the API Metadata can only be downloaded after authentication at api.sap.com I can't provide it directly here.

**Comment by MartinPankraz** [comment]
Thanks for pointing out. Would you consider the SAP Cloud SDK for Node instead?

**Comment by gregorwolf** [comment]
For the moment that is of course the best alternative if I need support for TypeScript or Java.

**Comment by MartinPankraz** [comment]
Ok, but you would favor the converter still?

**Comment by MartinPankraz** [comment]
@gregorwolf the issue was with the azure function. Moved everything into client now. Works on my end. Please retest :-)
